apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nanoaod-argo-
spec:
  entrypoint: nanoaod-argo
  volumes:
    - name: workdir
      hostPath:
        path: /mnt/data
        type: DirectoryOrCreate
  templates:
  - name: nanoaod-argo
    script:
      image: rootproject/root:6.22.08-ubuntu20.04
      command: [sh]
      source: |
        cd /mnt/vol
        ls  -l
        root -l -b <<EOF
        .pwd
        .pwd
        .q
         > EOF
        echo  ls -l /mnt/vol
        ls -l  /mnt/vol
      volumeMounts:
      - name: workdir
        mountPath: /mnt/vol
